# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 537)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.aEstrella = QtWidgets.QWidget()
        self.aEstrella.setObjectName("aEstrella")
        self.gridLayout = QtWidgets.QGridLayout(self.aEstrella)
        self.gridLayout.setObjectName("gridLayout")
        self.mapaAEstrella = QtWidgets.QLabel(self.aEstrella)
        self.mapaAEstrella.setText("")
        self.mapaAEstrella.setObjectName("mapaAEstrella")
        self.gridLayout.addWidget(self.mapaAEstrella, 0, 2, 1, 1)
        self.datosAEstrella = QtWidgets.QLabel(self.aEstrella)
        self.datosAEstrella.setObjectName("datosAEstrella")
        self.gridLayout.addWidget(self.datosAEstrella, 0, 0, 1, 1)
        self.ejecutaAEstrella = QtWidgets.QPushButton(self.aEstrella)
        self.ejecutaAEstrella.setObjectName("ejecutaAEstrella")
        self.gridLayout.addWidget(self.ejecutaAEstrella, 1, 0, 1, 1)
        self.tabWidget.addTab(self.aEstrella, "")
        self.hpaEstrella = QtWidgets.QWidget()
        self.hpaEstrella.setObjectName("hpaEstrella")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.hpaEstrella)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.datosHPA = QtWidgets.QLabel(self.hpaEstrella)
        self.datosHPA.setObjectName("datosHPA")
        self.gridLayout_3.addWidget(self.datosHPA, 0, 0, 1, 1)
        self.mapaHPA = QtWidgets.QLabel(self.hpaEstrella)
        self.mapaHPA.setText("")
        self.mapaHPA.setObjectName("mapaHPA")
        self.gridLayout_3.addWidget(self.mapaHPA, 0, 1, 1, 1)
        self.ejecutaHPA = QtWidgets.QPushButton(self.hpaEstrella)
        self.ejecutaHPA.setObjectName("ejecutaHPA")
        self.gridLayout_3.addWidget(self.ejecutaHPA, 1, 0, 1, 1)
        self.tabWidget.addTab(self.hpaEstrella, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Framework pathfinding"))
        self.datosAEstrella.setText(_translate("MainWindow", "Ejecuta el programa para A*"))
        self.ejecutaAEstrella.setText(_translate("MainWindow", "Ejecutar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aEstrella), _translate("MainWindow", "A*"))
        self.datosHPA.setText(_translate("MainWindow", "Ejecuta el programa para HPA*"))
        self.ejecutaHPA.setText(_translate("MainWindow", "Ejecutar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hpaEstrella), _translate("MainWindow", "HPA*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
